### ISSUE TITLE
library doesn't work with pandas v2.0.x

### ISSUE THREAD

**Issue by giordanocolombi** [man-group/PyBloqs#92]
Hi there,

I've noticed that the library doesn't work with pandas v2.0.x

`AttributeError: 'Series' object has no attribute 'append'`

or

` 'pandas.core.series.Series object' has no attribute 'iteritems'
`

Do you have a version compatible with the lastest version of pandas?

Best,
Giordano

**Comment by ArturSepp** [comment]
a manual fix to use pybloqs for pandas > 2.x:
locate file "...\Lib\site-packages\pybloqs\jinja\table.html" and 
change line 44 from
{% for col_name, cell in row.iteritems() %}
to
{% for col_name, cell in row.items() %}

**Comment by rspencer01** [comment]
This was actually fixed in #95
